name: Scala

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - 2.10.7
          - 2.11.12
          - 2.12.8
          - 2.12.9
          - 2.12.10
          - 2.13.0
          - 2.13.1

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v5
      with:
        java-version: openjdk@1.11.0
    - name: Run tests
      run: sbt ++${{matrix.scala}} test
